### ISSUE TITLE
Fix ts-check error: Type 'string' is not assignable to type '{ componentStack: string[]; }'. at src/layout/ErrorBoundary.js

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/dasher-user#158]
### Explication

This looks how a problem with types. Please to investigate what is the correct way to declare this types and implement

### Screenshots

![imagen](https://user-images.githubusercontent.com/66505715/142460270-a2fa506e-2a9e-4b8e-a7f9-f10f3cd34235.png)

https://github.com/Azordev/dasher-user/blob/dccbce3b5b6ea8af657388eec98dfaac7b201ff9/src/layouts/ErrorBoundary.js#L26-L36

### Checklist

- [ ] The reason why the error occurs is known
- [ ] Possible solutions were created
- [ ] It was decided between fixing the error or leaving it like that

**Comment by samuel-vergara-leon** [comment]
check that your tasks have the corresponding labels

**Comment by e-azocar** [comment]
This issue has solved in #104 because, currently the `Error` component isn't used

**Comment by e-azocar** [comment]
This is the current code of `ErrorBoundary` component, just render the JSX, and not import some component
![image](https://user-images.githubusercontent.com/61360270/151412255-7e4d57c8-e8cc-457c-9686-21b3b8565490.png)

**Comment by heliomar-pena** [comment]
I see that the component Error still is used at the Routes. 

Do u think that this component should be deleted?

Since we don't use it

![imagen](https://user-images.githubusercontent.com/66505715/151412678-3095c4d9-5ccb-40b6-92f4-6ccb0184f2a2.png)

**Comment by e-azocar** [comment]
So, can we close this issue?
